# Generated by Django 4.2.16 on 2024-12-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Catagory_image_url', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=10000000)),
                ('color', models.CharField(default='#8ecae6', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Character_image_url', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=10000000)),
                ('priority', models.IntegerField(blank=True, null=True, unique=True)),
                ('catagory', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='web.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('body', models.TextField(max_length=10000000)),
                ('hide_title', models.BooleanField(default=True, help_text='0-show, 1-hidden')),
                ('character', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='web.character')),
            ],
        ),
    ]
