# Generated by Django 4.2.16 on 2024-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_character_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
