# Generated by Django 4.2.16 on 2024-12-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_character_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='catagory',
        ),
        migrations.AddField(
            model_name='character',
            name='catagories',
            field=models.ManyToManyField(related_name='characters', to='web.catagory'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='priority',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character_details',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='character_details',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.character'),
        ),
    ]
