# Generated by Django 4.2.16 on 2024-12-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_character_catagory_character_catagories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='catagories',
        ),
        migrations.AddField(
            model_name='character',
            name='catagory',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='web.catagory'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='description',
            field=models.TextField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='character_details',
            name='body',
            field=models.TextField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='character_details',
            name='character',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='web.character'),
        ),
    ]
