# Generated by Django 4.2.16 on 2024-12-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_character_catagories_character_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
