# Generated by Django 4.2.16 on 2024-12-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_character_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='catagory',
        ),
        migrations.AddField(
            model_name='character',
            name='catagory',
            field=models.ManyToManyField(related_name='characters', to='web.catagory'),
        ),
    ]
