# Generated by Django 5.1.4 on 2025-01-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_character_catagory_character_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('op1', models.CharField(max_length=250)),
                ('op1_img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('op2', models.CharField(max_length=250)),
                ('op2_img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('op3', models.CharField(blank=True, max_length=250, null=True)),
                ('op3_img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('op4', models.CharField(blank=True, max_length=250, null=True)),
                ('op4_img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('ans', models.CharField(choices=[('op1', 'Option 1'), ('op2', 'Option 2'), ('op3', 'Option 3'), ('op4', 'Option 4')], max_length=3)),
            ],
        ),
    ]
