# Generated by Django 5.1.4 on 2025-01-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_quize'),
    ]

    operations = [
        migrations.AddField(
            model_name='quize',
            name='defaculty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
