# Generated by Django 5.1.4 on 2025-01-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_quize_defaculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='ans',
            field=models.CharField(choices=[(models.CharField(max_length=250), 'Option 1'), (models.CharField(max_length=250), 'Option 2'), (models.CharField(blank=True, max_length=250, null=True), 'Option 3'), (models.CharField(blank=True, max_length=250, null=True), 'Option 4')], max_length=3),
        ),
    ]
