# Generated by Django 5.1.4 on 2025-01-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_quize_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='ans',
            field=models.CharField(max_length=250),
        ),
    ]
