# Generated by Django 5.1.4 on 2025-01-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_quize_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='ans',
            field=models.CharField(choices=[('op1', 'option 1'), ('op2', 'option 2'), ('op3', 'option 3'), ('op4', 'option 4')], max_length=3),
        ),
    ]
